# Configuración mínima para Spring Boot
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/licoreria
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.main.banner-mode=off
# Habilitar logs DEBUG para diagnosticar Spring Security
logging.level.org.springframework.security=DEBUG
