# Este archivo es solo para evitar errores si no tienes log4j2.xml
# Puedes personalizarlo luego si lo necesitas
status = error
name = PropertiesConfig
filters = threshold
filter.threshold.type = ThresholdFilter
filter.threshold.level = debug
appenders = console
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d [%t] %-5level: %msg%n%throwable
loggers = root
logger.root.level = info
logger.root.appenderRefs = stdout
logger.root.appenderRef.stdout.ref = STDOUT
